// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZJaliQqra7Q-92_xvZCtDl0DSIvq5bE',
    appId: '1:166807333582:web:102067002ba7fbb31f7e9f',
    messagingSenderId: '166807333582',
    projectId: 'stellarbackend',
    authDomain: 'stellarbackend.firebaseapp.com',
    storageBucket: 'stellarbackend.firebasestorage.app',
    measurementId: 'G-8DE98YN0KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg4ysgof8G91IPmLx5H6VbONtHtNfhs9s',
    appId: '1:166807333582:android:b93681edd47a12091f7e9f',
    messagingSenderId: '166807333582',
    projectId: 'stellarbackend',
    storageBucket: 'stellarbackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfo8UkB1GE-8D7HFa0OpKzvarfEbKk1IE',
    appId: '1:166807333582:ios:de49744ee042b63b1f7e9f',
    messagingSenderId: '166807333582',
    projectId: 'stellarbackend',
    storageBucket: 'stellarbackend.firebasestorage.app',
    iosClientId: '166807333582-1ofdlusbm5os1ojs3ip8l7ohmhn41qhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stellarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfo8UkB1GE-8D7HFa0OpKzvarfEbKk1IE',
    appId: '1:166807333582:ios:de49744ee042b63b1f7e9f',
    messagingSenderId: '166807333582',
    projectId: 'stellarbackend',
    storageBucket: 'stellarbackend.firebasestorage.app',
    iosClientId: '166807333582-1ofdlusbm5os1ojs3ip8l7ohmhn41qhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stellarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkZJaliQqra7Q-92_xvZCtDl0DSIvq5bE',
    appId: '1:166807333582:web:ef160064bdd5413d1f7e9f',
    messagingSenderId: '166807333582',
    projectId: 'stellarbackend',
    authDomain: 'stellarbackend.firebaseapp.com',
    storageBucket: 'stellarbackend.firebasestorage.app',
    measurementId: 'G-J5F9YZZR0J',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_LINUX_MESSAGING_SENDER_ID',
    projectId: 'stellarproject',
    storageBucket: 'stellarproject.appspot.com',
  );
}
//test changes